# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
printWidth: 125
tabWidth: 4
semi: true
singleQuote: true
jsxSingleQuote: true
overrides:
  - files: '*.ts'
    options:
      parser: typescript
  - files: '*.html'
    options:
      parser: html
  - files: '*.vue'
    options:
      parser: vue
  - files:
      - '*.yml'
      - '*.yaml'
    options:
      tabWidth: 2
      parser: yaml
